### ISSUE TITLE
Bug in how ldap config is being applied

### ISSUE THREAD

**Issue by sandhujasmine** [ContinuumIO/flask-ldap-login#24]
See issue [#447](https://github.com/ContinuumIO/aen-issues/issues/447) and this [comment](https://github.com/ContinuumIO/aen-issues/issues/447#issuecomment-234651628) for the problem.

Saw this issue with Anaconda Repo for another client.

@dsludwig - shall I assign this to you since you've identified the source of the bug?

Copying @dsludwig's comment below:
This works (see http://python-ldap.cvs.sourceforge.net/viewvc/python-ldap/python-ldap/Demo/initialize.py?revision=1.9&view=markup):

```
import ldap
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_DEMAND)
ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, '/etc/ipa/ca.crt')
l = ldap.initialize('ldaps://ldap.example.com')
l.simple_bind_s('', '')
```

But this fails (see https://github.com/ContinuumIO/flask-ldap-login/blob/master/flask_ldap_login/__init__.py#L238-L247):

```
import ldap
l = ldap.initialize('ldaps://ldap.example.com')
l.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_DEMAND)
l.set_option(ldap.OPT_X_TLS_CACERTFILE, '/etc/ipa/ca.crt')
l.simple_bind_s('', '')
```

**Comment by dsludwig** [comment]
Hi @sandhujasmine, I have created an issue mirroring this in our internal repository (https://github.com/Anaconda-Platform/anaconda-server/issues/2644), so that it can be planned for a future sprint. Unfortunately, I didn't see this in time for it to make it into our current sprint (ending Aug 15).

**Comment by starcruiseromega** [comment]
I have a patch for this -- it's what I used to get our enterprise Anaconda server working with our LDAP over TLS. The code that @sandhujasmine posted above didn't work when I tried it with our LDAP. I'm not sure why unless it's a difference between using LDAPS or start_tls. Anyway I'll post a PR and you can let me know what you think.

**Comment by starcruiseromega** [comment]
https://github.com/ContinuumIO/flask-ldap-login/pull/25

**Comment by abarto** [comment]
A fix has already been merged.
